//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//------------------------------------------------------------------------------

namespace DigitalSignatureProject
{
    public partial class NextPage
    {
        protected global::System.Web.UI.WebControls.Literal litMessage;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pagesList;
        protected global::System.Web.UI.HtmlControls.HtmlIframe pdfFrame;
    }
}
